# Site settings
title: HTTP/2 and REST
email: fabian@consol.de
description: > # this means to ignore newlines until "baseurl:"
  REST, HTTP/2, Java Servlets, Go, and h2c.
# baseurl: "/h2c" # the subpath of your site, e.g. /blog/
#baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://fstab.github.io" # the base hostname & protocol for your site
# url: "http://192.168.59.103:4000"
twitter_username: fstabr
github_username:  fstab/h2c

# Build settings
markdown: kramdown

exclude: ['Gemfile','Gemfile.lock']
